doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                DATE: Gedmo\DoctrineExtensions\Query\PostgreSQL\Date
                DATEADD: Gedmo\DoctrineExtensions\Query\PostgreSQL\DateAdd
                DATESUB: Gedmo\DoctrineExtensions\Query\PostgreSQL\DateSub
                DATEDIFF: Gedmo\DoctrineExtensions\Query\PostgreSQL\DateDiff
                DAY: Gedmo\DoctrineExtensions\Query\PostgreSQL\Day
                DAYOFWEEK: Gedmo\DoctrineExtensions\Query\PostgreSQL\DayOfWeek
                DAYOFYEAR: Gedmo\DoctrineExtensions\Query\PostgreSQL\DayOfYear
                HOUR: Gedmo\DoctrineExtensions\Query\PostgreSQL\Hour
                MINUTE: Gedmo\DoctrineExtensions\Query\PostgreSQL\Minute
                MONTH: Gedmo\DoctrineExtensions\Query\PostgreSQL\Month
                SECOND: Gedmo\DoctrineExtensions\Query\PostgreSQL\Second
                WEEK: Gedmo\DoctrineExtensions\Query\PostgreSQL\Week
                WEEKDAY: Gedmo\DoctrineExtensions\Query\PostgreSQL\WeekDay
                YEAR: Gedmo\DoctrineExtensions\Query\PostgreSQL\Year
                YEARWEEK: Gedmo\DoctrineExtensions\Query\PostgreSQL\YearWeek
                TIMESTAMPADD: Gedmo\DoctrineExtensions\Query\PostgreSQL\TimestampAdd
                TIMESTAMPDIFF: Gedmo\DoctrineExtensions\Query\PostgreSQL\TimestampDiff
                IFELSE: Gedmo\DoctrineExtensions\Query\PostgreSQL\IfElse
                IFNULL: Gedmo\DoctrineExtensions\Query\PostgreSQL\IfNull
                NULLIF: Gedmo\DoctrineExtensions\Query\PostgreSQL\NullIf
                RAND: Gedmo\DoctrineExtensions\Query\PostgreSQL\Rand
                ROUND: Gedmo\DoctrineExtensions\Query\PostgreSQL\Round
                REPLACE: Gedmo\DoctrineExtensions\Query\PostgreSQL\Replace
                CONCAT_WS: Gedmo\DoctrineExtensions\Query\PostgreSQL\ConcatWs
                FIELD: Gedmo\DoctrineExtensions\Query\PostgreSQL\Field
                GREATEST: Gedmo\DoctrineExtensions\Query\PostgreSQL\Greatest
                LEAST: Gedmo\DoctrineExtensions\Query\PostgreSQL\Least
                SOUNDEX: Gedmo\DoctrineExtensions\Query\PostgreSQL\Soundex
                REGEXP: Gedmo\DoctrineExtensions\Query\PostgreSQL\Regexp
                BIT_AND: Gedmo\DoctrineExtensions\Query\PostgreSQL\BitAnd
                BIT_OR: Gedmo\DoctrineExtensions\Query\PostgreSQL\BitOr
                BIT_XOR: Gedmo\DoctrineExtensions\Query\PostgreSQL\BitXor
                BIT_NOT: Gedmo\DoctrineExtensions\Query\PostgreSQL\BitNot
                BIT_COUNT: Gedmo\DoctrineExtensions\Query\PostgreSQL\BitCount
                CAST: Gedmo\DoctrineExtensions\Query\PostgreSQL\Cast
                CONVERT: Gedmo\DoctrineExtensions\Query\PostgreSQL\Convert
                JSON_EXTRACT: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonExtract
                JSON_SEARCH: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonSearch
                JSON_CONTAINS: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonContains
                JSON_UNQUOTE: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonUnquote
                JSON_QUOTE: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonQuote
                JSON_DEPTH: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonDepth
                JSON_LENGTH: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonLength
                JSON_KEYS: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonKeys
                JSON_VALID: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonValid
                JSON_PRETTY: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonPretty
                JSON_TYPE: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonType
                JSON_VALUE: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonValue
                JSON_OVERLAPS: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonOverlaps
                JSON_OBJECT: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonObject
                JSON_ARRAY: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonArray
                JSON_MERGE: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonMerge
                JSON_MERGE_PATCH: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonMergePatch
                JSON_MERGE_PRESERVE: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonMergePreserve
                JSON_REMOVE: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonRemove
                JSON_SET: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonSet
                JSON_INSERT: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonInsert
                JSON_REPLACE: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonReplace
                JSON_ARRAY_APPEND: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonArrayAppend
                JSON_ARRAY_INSERT: Gedmo\DoctrineExtensions\Query\PostgreSQL\JsonArrayInsert
                UUID_SHORT: Gedmo\DoctrineExtensions\Query\PostgreSQL\UuidShort
                GROUP_CONCAT: Gedmo\DoctrineExtensions\Query\PostgreSQL\GroupConcat
                STD: Gedmo\DoctrineExtensions\Query\PostgreSQL\Std
                STDDEV: Gedmo\DoctrineExtensions\Query\PostgreSQL\Stddev
                STDDEVPOP: Gedmo\DoctrineExtensions\Query\PostgreSQL\Stddevpop
                STDDEVSAMP: Gedmo\DoctrineExtensions\Query\PostgreSQL\Stddevsamp
                VARIANCE: Gedmo\DoctrineExtensions\Query\PostgreSQL\Variance
                VARPOP: Gedmo\DoctrineExtensions\Query\PostgreSQL\Variancepop
                VARSAMP: Gedmo\DoctrineExtensions\Query\PostgreSQL\Varsamp
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
