doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        
        # MySQL requires backticks for quoting identifiers
        options:
            portability: 0

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\MySQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                DATE: Gedmo\DoctrineExtensions\Query\Mysql\Date
                DATEADD: Gedmo\DoctrineExtensions\Query\Mysql\DateAdd
                DATESUB: Gedmo\DoctrineExtensions\Query\Mysql\DateSub
                DATEDIFF: Gedmo\DoctrineExtensions\Query\Mysql\DateDiff
                DAY: Gedmo\DoctrineExtensions\Query\Mysql\Day
                DAYOFWEEK: Gedmo\DoctrineExtensions\Query\Mysql\DayOfWeek
                DAYOFYEAR: Gedmo\DoctrineExtensions\Query\Mysql\DayOfYear
                HOUR: Gedmo\DoctrineExtensions\Query\Mysql\Hour
                MINUTE: Gedmo\DoctrineExtensions\Query\Mysql\Minute
                MONTH: Gedmo\DoctrineExtensions\Query\Mysql\Month
                SECOND: Gedmo\DoctrineExtensions\Query\Mysql\Second
                WEEK: Gedmo\DoctrineExtensions\Query\Mysql\Week
                WEEKDAY: Gedmo\DoctrineExtensions\Query\Mysql\WeekDay
                YEAR: Gedmo\DoctrineExtensions\Query\Mysql\Year
                YEARWEEK: Gedmo\DoctrineExtensions\Query\Mysql\YearWeek
                TIMESTAMPADD: Gedmo\DoctrineExtensions\Query\Mysql\TimestampAdd
                TIMESTAMPDIFF: Gedmo\DoctrineExtensions\Query\Mysql\TimestampDiff
                IFELSE: Gedmo\DoctrineExtensions\Query\Mysql\IfElse
                IFNULL: Gedmo\DoctrineExtensions\Query\Mysql\IfNull
                NULLIF: Gedmo\DoctrineExtensions\Query\Mysql\NullIf
                RAND: Gedmo\DoctrineExtensions\Query\Mysql\Rand
                ROUND: Gedmo\DoctrineExtensions\Query\Mysql\Round
                REPLACE: Gedmo\DoctrineExtensions\Query\Mysql\Replace
                CONCAT_WS: Gedmo\DoctrineExtensions\Query\Mysql\ConcatWs
                FIELD: Gedmo\DoctrineExtensions\Query\Mysql\Field
                GREATEST: Gedmo\DoctrineExtensions\Query\Mysql\Greatest
                LEAST: Gedmo\DoctrineExtensions\Query\Mysql\Least
                SOUNDEX: Gedmo\DoctrineExtensions\Query\Mysql\Soundex
                REGEXP: Gedmo\DoctrineExtensions\Query\Mysql\Regexp
                BIT_AND: Gedmo\DoctrineExtensions\Query\Mysql\BitAnd
                BIT_OR: Gedmo\DoctrineExtensions\Query\Mysql\BitOr
                BIT_XOR: Gedmo\DoctrineExtensions\Query\Mysql\BitXor
                BIT_COUNT: Gedmo\DoctrineExtensions\Query\Mysql\BitCount
                CAST: Gedmo\DoctrineExtensions\Query\Mysql\Cast
                CONVERT: Gedmo\DoctrineExtensions\Query\Mysql\Convert
                JSON_EXTRACT: Gedmo\DoctrineExtensions\Query\Mysql\JsonExtract
                JSON_SEARCH: Gedmo\DoctrineExtensions\Query\Mysql\JsonSearch
                JSON_CONTAINS: Gedmo\DoctrineExtensions\Query\Mysql\JsonContains
                JSON_UNQUOTE: Gedmo\DoctrineExtensions\Query\Mysql\JsonUnquote
                JSON_QUOTE: Gedmo\DoctrineExtensions\Query\Mysql\JsonQuote
                JSON_DEPTH: Gedmo\DoctrineExtensions\Query\Mysql\JsonDepth
                JSON_LENGTH: Gedmo\DoctrineExtensions\Query\Mysql\JsonLength
                JSON_KEYS: Gedmo\DoctrineExtensions\Query\Mysql\JsonKeys
                JSON_VALID: Gedmo\DoctrineExtensions\Query\Mysql\JsonValid
                JSON_PRETTY: Gedmo\DoctrineExtensions\Query\Mysql\JsonPretty
                JSON_TYPE: Gedmo\DoctrineExtensions\Query\Mysql\JsonType
                JSON_VALUE: Gedmo\DoctrineExtensions\Query\Mysql\JsonValue
                JSON_OVERLAPS: Gedmo\DoctrineExtensions\Query\Mysql\JsonOverlaps
                JSON_OBJECT: Gedmo\DoctrineExtensions\Query\Mysql\JsonObject
                JSON_ARRAY: Gedmo\DoctrineExtensions\Query\Mysql\JsonArray
                JSON_MERGE: Gedmo\DoctrineExtensions\Query\Mysql\JsonMerge
                JSON_MERGE_PATCH: Gedmo\DoctrineExtensions\Query\Mysql\JsonMergePatch
                JSON_MERGE_PRESERVE: Gedmo\DoctrineExtensions\Query\Mysql\JsonMergePreserve
                JSON_REMOVE: Gedmo\DoctrineExtensions\Query\Mysql\JsonRemove
                JSON_SET: Gedmo\DoctrineExtensions\Query\Mysql\JsonSet
                JSON_INSERT: Gedmo\DoctrineExtensions\Query\Mysql\JsonInsert
                JSON_REPLACE: Gedmo\DoctrineExtensions\Query\Mysql\JsonReplace
                JSON_ARRAY_APPEND: Gedmo\DoctrineExtensions\Query\Mysql\JsonArrayAppend
                JSON_ARRAY_INSERT: Gedmo\DoctrineExtensions\Query\Mysql\JsonArrayInsert
                UUID_SHORT: Gedmo\DoctrineExtensions\Query\Mysql\UuidShort
                GROUP_CONCAT: Gedmo\DoctrineExtensions\Query\Mysql\GroupConcat
                STD: Gedmo\DoctrineExtensions\Query\Mysql\Std
                STDDEV: Gedmo\DoctrineExtensions\Query\Mysql\Stddev
                STDDEVPOP: Gedmo\DoctrineExtensions\Query\Mysql\Stddevpop
                STDDEVSAMP: Gedmo\DoctrineExtensions\Query\Mysql\Stddevsamp
                VARIANCE: Gedmo\DoctrineExtensions\Query\Mysql\Variance
                VARPOP: Gedmo\DoctrineExtensions\Query\Mysql\Variancepop
                VARSAMP: Gedmo\DoctrineExtensions\Query\Mysql\Varsamp
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
