nelmio_api_doc:
    documentation:
        info:
            title: API Documentation
            description: API for user management
            version: '1.0.0'
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas: # to filter documented areas
        default:
            path_patterns: [^/api]
            host_patterns: [.*]