version: "3.8"

services:
  db:
    image: postgres:15
    container_name: harba_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: harba
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tanasd79
    ports:
      - "8001:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - harba_network

  api-php:
    build:
      context: ./apps/api-php
      dockerfile: Dockerfile
    container_name: harba_api_php
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:tanasd79@db:5432/harba?serverVersion=15&sslmode=disable
    depends_on:
      - db
    volumes:
      - ./apps/api-php:/var/www
    networks:
      - harba_network

  nginx:
    image: nginx:alpine
    container_name: harba_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./apps/api-php:/var/www
    depends_on:
      - api-php
    networks:
      - harba_network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: harba_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    networks:
      - harba_network

volumes:
  db_data:

networks:
  harba_network:
    driver: bridge
